# Use custom format
format = """
$username\
$hostname\
$directory\
$gcloud\
${custom.firebase}\
$kubernetes\
$docker_context\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$direnv\
$fill\
$nodejs\
$python\
$c\
$golang\
$dart\
$java\
$dotnet\
$rlang\
$ruby\
$rust\
$helm\
$perl\
$php\
$nix_shell\
$opa\
$package\
$terraform\
$container\
$battery\
$cmd_duration $jobs \
$time\
$line_break\
$os\
$shell\
$sudo\
$status\
$character"""

# format = '$all'

# Inserts a blank line between shell prompts
add_newline = false

palette = "catppuccin_mocha"

[character]
success_symbol = '[➜](dimmed green) '
error_symbol = '[✗](dimmed red) '

[status]
style = 'bg:blue'
symbol = '🔴 '
# success_symbol = '🟢 SUCCESS'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[nodejs]
symbol = " "
format = "[$symbol($version  )]($style)"

[python]
symbol = "󰌠 "
format = "[$symbol($version  )]($style)"

[golang]
symbol = " "
# format = "[$symbol($version  )](bold cyan)"
format = "[$symbol($version )($mod_version )]($style)"

[fill]
symbol = " "

[directory]
style = "dimmed blue"
read_only = "🔒"
truncation_length = 4
truncate_to_repo = true

[gcloud]
symbol = "󱇶 "
format = 'logged on to [$symbol$account(@$domain)(\($project\))]($style) '

[jobs]
symbol = ''
style = 'red'
# number_threshold = 1
# format = '[$symbol]($style)'

[terraform]
format = '[󱁢 $version$workspace]($style ) '

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '

[git_branch]
truncation_length = 4
truncation_symbol = "…"

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = '💀 '

[kubernetes]
symbol = "󱃾 "
format = ' on [$symbol$context( \($namespace\))]($style) '
style = "dimmed green"
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]

[time]
disabled = false
format = '[\[󱑂 $time \]]($style) '
time_format = '%T'
utc_time_offset = '-5'

[shell]
fish_indicator = '󰈺 '
zsh_indicator = ''
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'dimmed cyan'
disabled = false

[cmd_duration]
min_time = 500

[os]
format = "[($symbol )]($style)"
style = "dimmed blue"
disabled = false

[custom.readme]
detect_files = ['README.md', 'README', 'readme.md']
# detect_folders = ['']
# detect_extensions = ['']
style = "red"
symbol = "R"
command = "wc -l readme* awk "
format = "[$symbol $output]($style)"

[custom.firebase]
symbol = "󰥧"
detect_files = ['firebase.json', '.firebaserc']
command = "firebase --version"
style = "#FFC400"
format = "[using $symbol Firebase ]($style)"
# format = "[$symbol $output]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

## Taken from https://starship.rs/presets/nerd-font
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '


[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "


[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
