#!/bin/sh

code --install-extension tht13.python
code --install-extension gerane.Theme-Solarized-dark
code --install-extension gerane.Theme-Solarized-ocean
code --install-extension ms-vscode.theme-markdownkit
code --install-extension swyphcosmo.spellchecker
code --install-extension formulahendry.terminal
code --install-extension mohsen1.prettify-json
code --install-extension karunamurti.haml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension  Pivotal.vscode-boot-java
code --install-extension Pivotal.vscode-boot-properties
code --install-extension ms-mssql.mssql
code --install-extension pivotal.vscode-boot-dev-pack
code --install-extension felipecaputo.git-project-manager
code --install-extension timonwong.shellcheck
code --install-extension magicstack.magicpython
code --install-extension codezombiech.gitignore
code --install-extension ms-vscode.csharp
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension waderyan.gitblame
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension rendandburns.vs-kubernetes
code --install-extension searking.preview-vscode
code --install-extension dotjoshjohnson.xml
code --install-extension vscjava.vscode-java-dependency
code --install-extension jamiewoodio.cisco
code --install-extension donjayamanne.githistory
code --install-extension mechatroner.rainbow-csv
code --install-extension hookyqr.beautify
code --install-extension vscjava.vscode-java-pack
code --install-extension ms-vscode.go
code --install-extension castwide.solargraph
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug4
code --install-extension vscjava.vscode-java-debug
code --install-extension ms-python.python
code --install-extension rebornix.ruby
code --install-extension vscjava.vscode-spring-initializr
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-java-test
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension mauve.terraform
code --install-extension vscjava.vscode-maven
code --install-extension redhat.java
code --install-extension mkaufman.htmlhint
code --install-extension peterjausovec.vscode-docker
code --install-extension jamiewoodio.cisco
code --install-extension vscjava.vscode-maven
code --install-extension ms-vscode.csharp
code --install-extension hookyqr.beautify
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension waderyan.gitblame
code --install-extension vscjava.vscode-java-dependency
code --install-extension castwide.solargraph
code --install-extension vscjava.vscode-java-test
code --install-extension redhat.vscode-yaml
code --install-extension ms-mssql.mssql
code --install-extension mauve.terraform
code --install-extension ms-python.python
code --install-extension pivotal.vscode-bosh
code --install-extension pivotal.vscode-concourse
code --install-extension pivotal.vscode-manifest-yaml
code --install-extension pivotal.vscode-spring-boot

